"use client";
import { useEffect,useRef,useState } from 'react';
import QRCode from 'qrcode';
import { api,ApiError } from '@/lib/api';
import { useStore } from '@/lib/store';
type Asset={id:string;name:string;qr_code:string;location:string|null;model:string|null;manufacturer:string|null;status:string;sop_slug:string;notes:string|null;next_service_date:string|null;warranty_expires:string|null;service_history:{id:string;kind:string;description:string;service_date:string;contractor:string|null}[]};
export default function AssetLibrary(){
 const {can}=useStore();const [assets,setAssets]=useState<Asset[]>([]),[id,setId]=useState(''),[asset,setAsset]=useState<Asset|null>(null),[error,setError]=useState(''),[qr,setQr]=useState(''),[sop,setSop]=useState(''),[link,setLink]=useState('');const request=useRef(0);
 useEffect(()=>{api<{items:Asset[]}>('/v1/assets').then(r=>{setAssets(r.items);setId(new URLSearchParams(window.location.search).get('id')||r.items[0]?.id||'');}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!id)return;const version=++request.current;setAsset(null);setQr('');setError('');api<Asset>(`/v1/assets/${id}`).then(async a=>{if(version!==request.current)return;setAsset(a);setSop(a.sop_slug??'');const url=new URL('/pocket/',window.location.origin);url.searchParams.set('asset',a.id);setLink(url.toString());const image=await QRCode.toDataURL(url.toString(),{width:220,margin:2,errorCorrectionLevel:'M'});if(version===request.current)setQr(image);}).catch(e=>{if(version===request.current)setError(e.message);});return()=>{request.current++;};},[id]);
 return <><div className="topbar"><div><h1>Equipment records & QR access</h1><p>Service history, operating notes and approved SOP references.</p></div></div>{error&&<div className="note" role="alert">{error}</div>}<label>Equipment<select className="readiness-select" value={id} onChange={e=>setId(e.target.value)}><option value="">Select equipment</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.location||'No location'}</option>)}</select></label>{!assets.length&&<p>No equipment records yet. Add records under Emergency & compliance.</p>}
 {asset&&<div className="split" style={{marginTop:20}}><section className="house-panel"><div className="k">{asset.qr_code}</div><h2>{asset.name}</h2><p>{[asset.manufacturer,asset.model,asset.location].filter(Boolean).join(' · ')}</p><p><b>Recorded status:</b> {asset.status.replace(/_/g,' ')}</p><p><b>Next service:</b> {asset.next_service_date?.slice(0,10)||'Not recorded'}</p><p><b>Warranty expiry:</b> {asset.warranty_expires?.slice(0,10)||'Not recorded'}</p><p style={{whiteSpace:'pre-wrap'}}>{asset.notes||'No operating notes recorded.'}</p><p>Follow the approved SOP and operating restrictions. This record is not a safety clearance.</p>
 {asset.sop_slug&&<a className="btn" href={`/manual/?slug=${encodeURIComponent(asset.sop_slug)}`}>Open equipment SOP</a>}
 {can('maintenance.work')&&<form className="ops-form" onSubmit={async e=>{e.preventDefault();try{await api(`/v1/assets/${asset.id}/sop`,{method:'PATCH',body:JSON.stringify({sop_slug:sop})});setAsset({...asset,sop_slug:sop});setError('');}catch(e){setError(e instanceof ApiError?e.problem.detail:'Could not save SOP.');}}}><label>Approved manual slug<input value={sop} maxLength={80} onChange={e=>setSop(e.target.value)}/></label><button className="btn">Save SOP reference</button></form>}
 <h3>Service history</h3>{asset.service_history.length?asset.service_history.map(h=><div className="ops-card" key={h.id}><b>{h.service_date.slice(0,10)} · {h.kind}</b><p>{h.description}</p><p className="m">{h.contractor}</p></div>):<p>No service history recorded.</p>}</section>
 <section className="house-panel"><div className="asset-qr-label"><h2>{asset.name}</h2>{qr&&<img src={qr} alt={`QR code for ${asset.name} staff equipment record`} width={220} height={220}/>}<p>{asset.qr_code}</p><p>Scan to open the staff equipment record. Staff sign-in is required.</p></div><p className="m" style={{overflowWrap:'anywhere'}}>{link}</p><button className="btn" onClick={()=>window.print()}>Print equipment label</button></section></div>}</>;
}
