"use client";
import {useEffect,useState}from'react';import{api,ApiError}from'@/lib/api';import{useStore}from'@/lib/store';
type Snapshot={employees:{id:number;name:string;departments:number[]}[];departments:{id:number;name:string}[];shifts:{id:number;employeeId:number|null;departmentId:number|null;date:string;start:string;end:string;timeZone:string;status:string}[];clock:{id:number;employeeId:number|null;departmentId:number|null;shiftId:number|null;start:string;end:string;approved:boolean}[]};
type Status={connected:boolean;secureStorageReady:boolean;canConfigure:boolean;lastSyncedAt:string|null;from:string;to:string;snapshot:Snapshot|null};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'});
export default function PlandayConnection(){const {can}=useStore();const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clientId,setClientId]=useState(''),[secret,setSecret]=useState(''),[consent,setConsent]=useState(false),[from,setFrom]=useState(today),[to,setTo]=useState(today),[query,setQuery]=useState(''),[view,setView]=useState<'shifts'|'clock'|'employees'>('shifts');
 const permitted=can('clock.manage');const load=async()=>{try{const s=await api<Status>('/v1/planday');setStatus(s);}catch(e){setError(e instanceof ApiError?e.problem.detail:'Could not load Planday status.');}};
 useEffect(()=>{if(permitted)void load();},[permitted]);
 if(!permitted)return null;
 const action=async(path:string,body?:unknown,method='POST')=>{setBusy(true);setError('');try{await api(path,{method,body:body?JSON.stringify(body):undefined});setSecret('');await load();}catch(e){setError(e instanceof ApiError?e.problem.detail:'The Planday request failed.');}finally{setBusy(false);}};
 const s=status?.snapshot;const employee=(id:number|null)=>s?.employees.find(e=>e.id===id)?.name??(id?`Employee ${id}`:'Unassigned');const department=(id:number|null)=>s?.departments.find(d=>d.id===id)?.name??(id?`Department ${id}`:'—');
 const matches=(name:string)=>name.toLowerCase().includes(query.trim().toLowerCase());
 return <section className="house-panel" style={{margin:'20px 0'}} aria-label="Planday integration"><div className="kicker">Workforce connection</div><h2>Planday</h2><p>Read-only staff, rota and Punch Clock overview. Planday remains the source of truth: this connection does not change shifts, approve timesheets or run payroll.</p>
 {error&&<p className="note" role="alert">{error}</p>}{!status?<p>Checking connection…</p>:<>
 <p><b>{status.connected?'Authorised connection':'Not connected'}</b>{status.lastSyncedAt?` · Last successful sync: ${new Date(status.lastSyncedAt).toLocaleString('en-GB')}`:' · No staff data has been synced.'}</p>
 {!status.connected&&<><details open><summary>How to connect your Planday portal</summary><ol><li>As a Planday administrator, open Settings → Integrations → API Access.</li><li>Create an app named “Vedanta read-only”. Choose only Employee read, Department read, Shifts read and Punch Clock read.</li><li>Authorise it in Planday, then enter its App ID and token below. Do not send the token in chat or commit it to GitHub.</li></ol><a href="https://developer.planday.com/gettingstarted/authorization#authorization-flow-for-customers" target="_blank" rel="noreferrer">Official Planday setup guide ↗</a></details>
 {!status.secureStorageReady&&<p className="note">Secure token storage needs to be enabled on the server before you can connect.</p>}
 {status.canConfigure?<form onSubmit={e=>{e.preventDefault();void action('/v1/planday/connect',{clientId,refreshToken:secret,consent});}} style={{display:'grid',gap:12,maxWidth:600,marginTop:16}}><label>App ID<input autoComplete="off" required value={clientId} onChange={e=>setClientId(e.target.value)} disabled={busy||!status.secureStorageReady}/></label><label>Refresh token<input type="password" autoComplete="new-password" required value={secret} onChange={e=>setSecret(e.target.value)} disabled={busy||!status.secureStorageReady}/></label><label style={{display:'flex',gap:8}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I administer this Planday portal and approve importing staff names, departments, shifts and Punch Clock records into this Vedanta property.</label><button className="btn primary" disabled={busy||!consent||!status.secureStorageReady}>{busy?'Connecting…':'Connect Planday'}</button></form>:<p>Your Vedanta administrator must set up the connection.</p>}</>}
 {status.connected&&<><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end',margin:'16px 0'}}><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn primary" disabled={busy} onClick={()=>void action('/v1/planday/sync',{from,to})}>{busy?'Reading Planday…':'Sync selected dates'}</button></div><p className="m">Up to 31 days per sync. A new successful sync replaces this view of Planday data, not your Vedanta staff or rota records. No automatic employee matching or payroll changes.</p></>}
 {s&&<><p><b>{s.employees.length}</b> staff · <b>{s.shifts.length}</b> shifts · <b>{s.clock.length}</b> clock records · {status.from} to {status.to}</p><label>Find Planday staff or department<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search staff / department"/></label><div className="seg" style={{margin:'16px 0'}}>{(['shifts','clock','employees'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='clock'?'Punch Clock':v==='employees'?'Staff':'Rota'}</button>)}</div><div style={{overflowX:'auto'}}><table style={{width:'100%',fontSize:12,borderCollapse:'collapse'}}><thead><tr>{(view==='employees'?['Staff','Departments']:['Staff','Department','Start','End',view==='clock'?'Approval':'Status / timezone']).map(h=><th key={h} style={{textAlign:'left',padding:10}}>{h}</th>)}</tr></thead><tbody>{view==='employees'?s.employees.filter(e=>matches(e.name+' '+e.departments.map(department).join(' '))).map(e=><tr key={e.id}><td style={{padding:10}}>{e.name}</td><td>{e.departments.map(department).join(', ')}</td></tr>):(view==='clock'?s.clock:s.shifts).filter(r=>matches(employee(r.employeeId)+' '+department(r.departmentId))).map(r=><tr key={r.id} style={{borderTop:'1px solid var(--rule)'}}><td style={{padding:10}}>{employee(r.employeeId)}</td><td>{department(r.departmentId)}</td><td>{r.start.replace('T',' ')||'—'}</td><td>{r.end.replace('T',' ')||'Still open'}</td><td>{'approved'in r?(r.approved?'Approved':'Not approved'):`${r.status} · ${r.timeZone}`}</td></tr>)}</tbody></table></div><p className="m">Times are shown as supplied by Planday. Clock spans are not paid hours: breaks, rounding rules and payroll calculations are not applied here.</p></>}
 {status.connected&&status.canConfigure&&<details style={{marginTop:20}}><summary>Disconnect</summary><p>This removes the stored token and imported snapshot from Vedanta. It does not delete anything in Planday. Revoke the app in Planday API Access to end its authorisation there too.</p><button className="btn" disabled={busy} onClick={()=>{if(window.confirm('Remove this Planday connection and its imported snapshot from Vedanta? Nothing in Planday will be changed.'))void action('/v1/planday',undefined,'DELETE');}}>Disconnect Planday</button></details>}
 </>}</section>;
}
