import{test}from'node:test';import assert from'node:assert/strict';import{sealToken,openToken,refreshPlanday,plandayList,minimiseSnapshot}from'./planday-client.ts';
test('tokens are authenticated, encrypted and bound to one property',()=>{const old=process.env.PLANDAY_TOKEN_ENCRYPTION_KEY;process.env.PLANDAY_TOKEN_ENCRYPTION_KEY='a'.repeat(64);try{const sealed=sealToken('test-only-refresh','property-one');assert.ok(!sealed.includes('test-only-refresh'));assert.equal(openToken(sealed,'property-one'),'test-only-refresh');assert.throws(()=>openToken(sealed,'property-two'));assert.notEqual(sealed,sealToken('test-only-refresh','property-one'));}finally{if(old===undefined)delete process.env.PLANDAY_TOKEN_ENCRYPTION_KEY;else process.env.PLANDAY_TOKEN_ENCRYPTION_KEY=old;}});
test('refresh uses the official endpoint and retains a rotated token',async()=>{const r=await refreshPlanday('app-id','test-refresh',async(url,init)=>{assert.equal(url,'https://id.planday.com/connect/token');assert.equal(init?.method,'POST');assert.equal((init?.body as URLSearchParams).get('grant_type'),'refresh_token');return new Response(JSON.stringify({access_token:'test-access',refresh_token:'rotated'}));});assert.equal(r.refreshToken,'rotated');});
test('read lists paginate and use only official GET endpoints',async()=>{let calls=0;const rows=await plandayList('employees','app-id','token',{from:'2026-10-01',to:'2026-10-05'},async(url,init)=>{calls++;assert.equal(new URL(String(url)).origin,'https://openapi.planday.com');assert.equal(init?.method,undefined);assert.equal(new URL(String(url)).searchParams.get('offset'),calls===1?'0':'1');return new Response(JSON.stringify({data:[{id:calls}],paging:{total:2}}));});assert.equal(rows.length,2);});
test('upstream errors never expose its response body or token',async()=>{await assert.rejects(()=>plandayList('clock','app-id','SECRET',{from:'2026-10-01',to:'2026-10-05'},async()=>new Response('SECRET staff data',{status:403})),e=>e instanceof Error&&!e.message.includes('SECRET')&&e.message.includes('access'));});
test('unexpected or repeated pagination fails rather than delivering partial staff data',async()=>{await assert.rejects(()=>plandayList('employees','id','token',{from:'2026-10-01',to:'2026-10-05'},async()=>new Response(JSON.stringify({data:[{id:1}],paging:{total:2}}))),/pagination/);});

test('a shared sync deadline stops further pagination',async()=>{const controller=new AbortController();let calls=0;await assert.rejects(()=>plandayList('employees','id','token',{from:'2026-10-01',to:'2026-10-05',signal:controller.signal},async()=>{calls++;controller.abort();return new Response(JSON.stringify({data:[{id:1}],paging:{total:2}}));}),/abort/i);assert.equal(calls,1);});
test('snapshot excludes bank, email, home address, salary, birth date and comments',()=>{const s=minimiseSnapshot([{id:1,firstName:'Test',lastName:'Person',email:'PRIVATE',bankAccount:'PRIVATE',departments:[2]}],[{id:2,name:'Kitchen'}],[{id:3,employeeId:1,comment:'PRIVATE',startDateTime:'2026-10-01T08:00',endDateTime:'2026-10-01T16:00'}],[{id:4,employeeId:1,isApproved:true,salaryNote:'PRIVATE'}]);assert.ok(!JSON.stringify(s).includes('PRIVATE'));assert.equal(s.employees[0].name,'Test Person');assert.equal(s.clock[0].approved,true);});
