import type { FastifyInstance } from 'fastify';
import { pool,tx } from './db.ts';
import { requireActor,allow,problem } from './auth.ts';
import { audit } from './groups.ts';
import { parseUuid } from '../../../domains/ops/tasks.ts';
export default async function staffAssets(f:FastifyInstance){
 const reader=async(req:any,reply:any)=>{const a=await requireActor(req,reply,['ADMIN','STAFF']);if(!a)return null;if(!['task.read','maintenance.read','covers.read','group.read'].some(p=>a.perms.has(p))){reply.code(403).send(problem(403,'forbidden','Equipment access requires an operations role.'));return null;}return a;};
 f.get('/v1/staff/assets',async(req,reply)=>{const a=await reader(req,reply);if(!a)return;return {items:(await pool.query(`select id,name,location,status,qr_code from asset where property_id=$1 and status <> 'disposed' order by name`,[a.propertyId])).rows};});
 f.get('/v1/staff/assets/:id',async(req:any,reply)=>{const a=await reader(req,reply);if(!a)return;if(!parseUuid(req.params.id))return reply.code(422).send(problem(422,'validation','Invalid equipment ID'));const asset=(await pool.query(`select id,name,location,manufacturer,model,status,qr_code,notes,sop_slug,next_service_date::text from asset where id=$1 and property_id=$2`,[req.params.id,a.propertyId])).rows[0];if(!asset)return reply.code(404).send(problem(404,'not_found','Equipment not found'));const history=(await pool.query(`select id,kind,description,service_date::text,contractor from asset_service_record where asset_id=$1 order by service_date desc`,[asset.id])).rows;return {...asset,service_history:history};});
 f.patch('/v1/assets/:id/sop',async(req:any,reply)=>{const a=await requireActor(req,reply);if(!a||!allow(a,'maintenance.work',reply))return;const slug=String(req.body?.sop_slug??'').trim();if(!parseUuid(req.params.id)||slug.length>80||slug&&!/^[a-z0-9-]+$/.test(slug))return reply.code(422).send(problem(422,'validation','Use a valid approved manual slug.'));return tx(async c=>{if(slug&&!(await c.query(`select id from house_manual where property_id=$1 and slug=$2 and status='live'`,[a.propertyId,slug])).rowCount)throw Object.assign(new Error('No approved manual with that slug at this property.'),{status:422,code:'invalid_sop'});const r=await c.query(`update asset set sop_slug=$3 where id=$1 and property_id=$2 returning id`,[req.params.id,a.propertyId,slug]);if(!r.rowCount)return reply.code(404).send(problem(404,'not_found','Equipment not found'));await audit(c,a,'asset',req.params.id,'asset.sop.update',{payload:{sop_slug:slug}});return {ok:true};});});
}
