#!/usr/bin/env python3
"""
Room Sheet importer: person × room × half-day → room_occupancy.

The Room Sheet has rooms down the side and one column per half-day (AM/PM) across the year.
A name written once and merged across several columns is a stay. Names are placed under the
group booking that is in house on that date when there is exactly one; otherwise group_id is
left empty for staff to fix on the board.

Usage: python3 import_roomsheet.py <sheet.xlsx> <out.sql> [year ...]
"""
import sys, re, datetime as dt
from openpyxl import load_workbook

MONTHS = {m: i for i, m in enumerate(["JANUARY","FEBRUARY","MARCH","APRIL","MAY","JUNE","JULY","AUGUST","SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER"], 1)}
MONTHS.update({m[:3]: i for m, i in list(MONTHS.items())})  # 2025 sheet uses JAN, FEB, ...
SKIP = {"", "SPARE", "X", "OUT OF USE", "OOU", "N/A", "-", "SINGLE OCC", "TBC"}

def q(s): return "'" + str(s).replace("'", "''") + "'"

def columns(ws, year):
    """Map column index → (date, slot). Header rows are found, not assumed: the row containing
    AM/PM is the slot row, the row above it holds day numbers, and month names sit in any row above."""
    rows = [[c.value for c in r] for r in ws.iter_rows(min_row=1, max_row=8)]
    slot_row = next(i for i, r in enumerate(rows) if sum(1 for v in r if v in ("AM", "PM")) > 20)
    day_row = slot_row - 1
    month = None; out = {}
    for i in range(len(rows[slot_row])):
        for mr in range(0, slot_row + 1):  # month labels sit above the days in 2026, on the slot row in 2025
            v = rows[mr][i] if i < len(rows[mr]) else None
            if isinstance(v, str) and v.strip().upper() in MONTHS: month = MONTHS[v.strip().upper()]
        d = rows[day_row][i] if i < len(rows[day_row]) else None; s = rows[slot_row][i]
        if month and d is not None and s in ("AM", "PM"):
            try:
                nd = dt.date(year, month, int(float(d)))
                if out and nd < max(v[0] for v in out.values()) - dt.timedelta(days=40): continue  # stray header cell
                out[i] = (nd, s)
            except ValueError: pass
    return out, slot_row + 2

def run(path, out_path, years):
    wb = load_workbook(path)  # not read-only: we need merged ranges
    sql = ["-- Generated by tools/import-sheet/import_roomsheet.py", "BEGIN;"]
    total = 0; unmatched = 0
    for year in years:
        name = f"{year} Room Sheet"
        if name not in wb.sheetnames: print("no sheet", name); continue
        ws = wb[name]; cols, first_row = columns(ws, year)
        col_list = sorted(cols)  # column indexes (0-based) that carry a half-day
        stays = []; unknown_rooms = set()
        def filled(cell): return bool(cell.fill and cell.fill.fill_type == "solid" and cell.fill.fgColor and cell.fill.fgColor.rgb not in (None, "00000000", "FFFFFFFF"))
        for row in ws.iter_rows(min_row=first_row):
            a = row[0].value
            if a is None: continue
            room = str(a).replace(".0", "").strip()
            if not (room[:1] == "G" and room[1:].isdigit()) and not room.isdigit(): continue
            if room in ("301","302","303","304","305","306","307"): unknown_rooms.add(room); continue  # not in the 2026 inventory — confirm with Shyam
            # Walk the row as coloured runs. Every name written inside one run shares the room for
            # the rest of that run (a twin has two names in adjacent cells). If a run holds more
            # names than the room sleeps, staff wrote sequential guests: fall back to one-after-another.
            nums = [int(float(c.value)) for c in row[1:7] if isinstance(c.value, (int, float))]
            cap = max(nums) if nums else 2  # the "Max capacity" column moves between years; it is always the largest number
            k = 0
            while k < len(col_list):
                ci = col_list[k]; cell = row[ci]
                if cell.value is None and not filled(cell): k += 1; continue
                run = []
                while k < len(col_list):
                    c = row[col_list[k]]
                    if c.value is None and not filled(c): break
                    if run and c.value is not None and not filled(c) and not filled(row[col_list[k - 1]]): break  # uncoloured name = new entry
                    run.append(k); k += 1
                names = [(j, re.sub(r"\s+", " ", str(row[col_list[j]].value)).strip()) for j in run if row[col_list[j]].value is not None]
                names = [(j, n) for j, n in names if n.upper() not in SKIP]
                if not names: continue
                if len(names) <= cap:
                    for j, n in names: stays.append((room, n, [cols[col_list[x]] for x in run if x >= j]))
                else:
                    for idx, (j, n) in enumerate(names):
                        end = names[idx + 1][0] if idx + 1 < len(names) else run[-1] + 1
                        stays.append((room, n, [cols[col_list[x]] for x in run if j <= x < end]))
        for room, label, hds in stays:
            first, last = hds[0][0], hds[-1][0]
            for d, s in hds:
                total += 1
                sql.append(f"""INSERT INTO room_occupancy (tenant_id, room_id, group_id, occupant_label, on_date, slot)
  SELECT r.tenant_id, r.id,
    (SELECT g.id FROM booking_group g WHERE g.property_id=r.property_id AND g.status <> 'CANCELLED'
       AND g.arrival_date <= {q(d)} AND g.departure_date >= {q(d)} AND g.expected_rooms IS DISTINCT FROM 0
       AND (SELECT count(*) FROM booking_group g2 WHERE g2.property_id=r.property_id AND g2.status <> 'CANCELLED'
            AND g2.arrival_date <= {q(d)} AND g2.departure_date >= {q(d)} AND g2.expected_rooms IS DISTINCT FROM 0) = 1),
    {q(label)}, {q(d)}, {q(s)}
  FROM room r WHERE r.number={q(room)}
    AND NOT EXISTS (SELECT 1 FROM booking_group g WHERE g.property_id=r.property_id AND g.status <> 'CANCELLED' AND g.expected_rooms IS DISTINCT FROM 0
                    AND g.arrival_date <= {q(first)} AND g.departure_date >= {q(first)}
                    AND (g.departure_date < {q(d)} OR (g.departure_date = {q(d)} AND g.departure_slot = 'AM' AND {q(s)} = 'PM'))
                    AND (SELECT count(*) FROM booking_group g2 WHERE g2.property_id=r.property_id AND g2.status <> 'CANCELLED' AND g2.expected_rooms IS DISTINCT FROM 0
                         AND g2.arrival_date <= {q(first)} AND g2.departure_date >= {q(first)}) = 1)
  ON CONFLICT DO NOTHING;""")
        print(f"{name}: {len(stays)} stays, {sum(len(h) for _,_,h in stays)} half-days" + (f"; skipped rooms not in inventory: {sorted(unknown_rooms)}" if unknown_rooms else ""))
    sql.append("COMMIT;")
    open(out_path, "w").write("\n".join(sql))
    print(f"wrote {out_path}: {total} rows")

if __name__ == "__main__":
    yrs = [int(y) for y in sys.argv[3:]] or [2025, 2026]
    run(sys.argv[1], sys.argv[2], yrs)
