"use client";
import { useEffect,useState } from 'react';import { api } from '../lib/api';
type Asset={id:string;name:string;status:string;location:string;notes:string|null;sop_slug:string;next_service_date:string|null;service_history:{id:string;kind:string;description:string;service_date:string}[]};
type Manual={title:string;body:string;status:string;steps:{title:string;look:string;act:string}[]};
export default function StaffAssetViewer({initialId}:{initialId:string}){
 const [list,setList]=useState<Asset[]>([]),[id,setId]=useState(initialId),[asset,setAsset]=useState<Asset|null>(null),[manual,setManual]=useState<Manual|null>(null),[error,setError]=useState('');
 useEffect(()=>{api<{items:Asset[]}>('/v1/staff/assets').then(r=>{setList(r.items);if(!initialId)setId(r.items[0]?.id??'');}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(initialId)setId(initialId);},[initialId]);
 useEffect(()=>{let active=true;setAsset(null);setManual(null);setError('');if(id)api<Asset>(`/v1/staff/assets/${id}`).then(async a=>{if(!active)return;setAsset(a);sessionStorage.removeItem('vedanta.asset.intent');if(a.sop_slug){try{const m=await api<Manual>(`/v1/manuals/${encodeURIComponent(a.sop_slug)}`);if(active&&m.status==='live')setManual(m);}catch{}}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);
 return <div className="card"><h2>Equipment records</h2><label>Equipment<select value={id} onChange={e=>setId(e.target.value)}><option value="">Select equipment</option>{list.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{error&&<p className="note" role="alert">{error}</p>}{asset&&<><h2>{asset.name}</h2><p>{asset.location} · {asset.status.replace(/_/g,' ')}</p><p>Next service: {asset.next_service_date||'Not recorded'}</p><p style={{whiteSpace:'pre-wrap'}}>{asset.notes||'No operating notes recorded.'}</p><p className="note">Follow approved operating restrictions. This record does not certify safe use.</p>{manual?<details open><summary>{manual.title}</summary><p>{manual.body}</p>{manual.steps.map((s,i)=><div key={i}><h3>{i+1}. {s.title}</h3><p>{s.look}</p><p>{s.act}</p></div>)}</details>:<p>No active SOP linked. Ask the department lead for approved instructions.</p>}<h3>Service history</h3>{asset.service_history.map(h=><div key={h.id}><b>{h.service_date} · {h.kind}</b><p>{h.description}</p></div>)}</>}</div>;
}
